package com.exception;
/**
	@author:sunjunya
*/
public class TestFinally {

	public static void main(String[] args) {
		int num=10;
	//	System.out.println(test(num));
		int a=0b10;
		int b=0b01;
//		
//		boolean t=true;
//		String c="12";
//		System.out.println(c+t);
//		
//		
//		System.out.println(a+b);
		
		long  l=1234;
		float f=3.1f;
		f=l;
		System.out.println(f);
	
	}

	public static int test(int num) {
		try {
			num+=10;
			return num;
		} catch(RuntimeException e){
			
		}
		finally {
			num+=10;
			return num;
		}
	}

}
